import { readFileSync } from "node:fs";
import path from "node:path";
import type { GithubData, Repo } from "@/lib/github";

// Generated by `pnpm fetch-data` (scripts/fetch-github-data.mjs); not committed.
function load(): GithubData {
    try {
        return JSON.parse(readFileSync(path.join(process.cwd(), "data", "github.json"), "utf8"));
    } catch {
        console.warn("data/github.json not found, run `pnpm fetch-data` first. Rendering without repos.");
        return {
            generatedAt: new Date().toISOString(),
            profile: { login: "StijnRis", name: null, avatarUrl: "https://github.com/StijnRis.png", url: "https://github.com/StijnRis", followers: 0, publicRepos: 0 },
            totals: { repos: 0, stars: 0, commits: 0, linesChanged: 0, daysWorked: 0, hackathons: 0, languages: [] },
            repos: [],
        };
    }
}

export const github = load();

export function getRepo(name: string): Repo | undefined {
    return github.repos.find((r) => r.name === name);
}
